// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package watch

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type watchEvent struct {
	_    structs.HostLayout
	Op   uint8
	Pad  [3]uint8
	Pid  int32
	Dfd  int32
	Name [4096]int8
}

// loadWatch returns the embedded CollectionSpec for watch.
func loadWatch() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_WatchBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load watch: %w", err)
	}

	return spec, err
}

// loadWatchObjects loads watch and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*watchObjects
//	*watchPrograms
//	*watchMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadWatchObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadWatch()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// watchSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type watchSpecs struct {
	watchProgramSpecs
	watchMapSpecs
	watchVariableSpecs
}

// watchProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type watchProgramSpecs struct {
	OnCreat     *ebpf.ProgramSpec `ebpf:"on_creat"`
	OnOpen      *ebpf.ProgramSpec `ebpf:"on_open"`
	OnOpenat    *ebpf.ProgramSpec `ebpf:"on_openat"`
	OnOpenat2   *ebpf.ProgramSpec `ebpf:"on_openat2"`
	OnRename    *ebpf.ProgramSpec `ebpf:"on_rename"`
	OnRenameat  *ebpf.ProgramSpec `ebpf:"on_renameat"`
	OnRenameat2 *ebpf.ProgramSpec `ebpf:"on_renameat2"`
	OnUnlink    *ebpf.ProgramSpec `ebpf:"on_unlink"`
	OnUnlinkat  *ebpf.ProgramSpec `ebpf:"on_unlinkat"`
}

// watchMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type watchMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// watchVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type watchVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// watchObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadWatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type watchObjects struct {
	watchPrograms
	watchMaps
	watchVariables
}

func (o *watchObjects) Close() error {
	return _WatchClose(
		&o.watchPrograms,
		&o.watchMaps,
	)
}

// watchMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadWatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type watchMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *watchMaps) Close() error {
	return _WatchClose(
		m.Events,
	)
}

// watchVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadWatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type watchVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// watchPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadWatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type watchPrograms struct {
	OnCreat     *ebpf.Program `ebpf:"on_creat"`
	OnOpen      *ebpf.Program `ebpf:"on_open"`
	OnOpenat    *ebpf.Program `ebpf:"on_openat"`
	OnOpenat2   *ebpf.Program `ebpf:"on_openat2"`
	OnRename    *ebpf.Program `ebpf:"on_rename"`
	OnRenameat  *ebpf.Program `ebpf:"on_renameat"`
	OnRenameat2 *ebpf.Program `ebpf:"on_renameat2"`
	OnUnlink    *ebpf.Program `ebpf:"on_unlink"`
	OnUnlinkat  *ebpf.Program `ebpf:"on_unlinkat"`
}

func (p *watchPrograms) Close() error {
	return _WatchClose(
		p.OnCreat,
		p.OnOpen,
		p.OnOpenat,
		p.OnOpenat2,
		p.OnRename,
		p.OnRenameat,
		p.OnRenameat2,
		p.OnUnlink,
		p.OnUnlinkat,
	)
}

func _WatchClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed watch_bpfeb.o
var _WatchBytes []byte
